require('dotenv').config();
const express = require('express');
const cors = require('cors');
const { createClient } = require('@supabase/supabase-js');

const app = express();
app.use(cors());

const supabaseUrl = process.env.SUPABASE_URL || 'https://mock.supabase.co';
const supabaseKey = process.env.SUPABASE_KEY || 'mock-key';
const supabase = createClient(supabaseUrl, supabaseKey);

app.get('/api/certificates/generate/:worker_id', async (req, res) => {
    const { worker_id } = req.params;
    
    // Fetch verified earnings from Supabase for this worker_id
    const { data: earnings } = await supabase
        .from('earnings')
        .select('*')
        .eq('worker_id', worker_id)
        .eq('status', 'verified');
    
    const { data: user } = await supabase.from('users').select('email').eq('id', worker_id).single();

    let totalHours = 0;
    let totalNet = 0;
    let platformData = {};

    if (earnings) {
        earnings.forEach(e => {
            if (!platformData[e.platform]) {
                platformData[e.platform] = { shifts: 0, hours: 0, net: 0 };
            }
            platformData[e.platform].shifts += 1;
            platformData[e.platform].hours += parseFloat(e.hours_worked);
            platformData[e.platform].net += parseFloat(e.net_received);

            totalHours += parseFloat(e.hours_worked);
            totalNet += parseFloat(e.net_received);
        });
    }

    const tableRows = Object.keys(platformData).map(p => `
        <tr>
            <td>${p}</td>
            <td>${platformData[p].shifts}</td>
            <td>${platformData[p].hours.toFixed(1)}</td>
            <td>Rs. ${platformData[p].net.toLocaleString()} <span class="verified-badge">✓</span></td>
        </tr>
    `).join('');

    const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Income Certificate - FairGig</title>
        <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; }
            .header { text-align: center; border-bottom: 2px solid #3b82f6; padding-bottom: 20px; margin-bottom: 30px; }
            .content { max-width: 800px; margin: 0 auto; }
            .table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            .table th, .table td { border: 1px solid #ddd; padding: 12px; text-align: left; }
            .table th { background-color: #f8fafc; }
            .verified-badge { color: #10b981; font-weight: bold; }
            .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
        </style>
    </head>
    <body>
        <div class="content">
            <div class="header">
                <h1 style="color: #3b82f6;">FairGig</h1>
                <h2>Verified Income Certificate</h2>
            </div>
            
            <p><strong>Worker:</strong> ${user?.email || worker_id}</p>
            <p><strong>Date Range:</strong> Lifetime Verified</p>
            <p>This document certifies the verified earnings logged on the FairGig platform.</p>
            
            <table class="table">
                <thead>
                    <tr>
                        <th>Platform</th>
                        <th>Shifts Logged</th>
                        <th>Total Hours</th>
                        <th>Net Earnings (Verified)</th>
                    </tr>
                </thead>
                <tbody>
                    ${tableRows || '<tr><td colspan="4">No verified earnings found.</td></tr>'}
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="3" style="text-align: right;">Total Verified Net Income:</th>
                        <th>Rs. ${totalNet.toLocaleString()}</th>
                    </tr>
                </tfoot>
            </table>
            
            <div class="footer">
                <p>Generated by FairGig Platform. This is an automatically generated document.</p>
                <p>Verification ID: FG-${Math.floor(Math.random() * 1000000)}</p>
            </div>
        </div>
        <script>
            // Auto trigger print dialog
            window.onload = function() { window.print(); }
        </script>
    </body>
    </html>
    `;
    
    res.send(htmlContent);
});

const PORT = process.env.PORT || 4003;
app.listen(PORT, () => {
    console.log(`Certificate Service running on port ${PORT}`);
});
